import Head from 'next/head'

import styles from '../styles/Home.module.scss'

import Form from '../components/Form/Form'
import FinalEnteredData from '../components/CompleteProfile.tsx/FinalEnteredData'


const Home = () =>{
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Form/>
        {/* <FinalEnteredData/> */}
      </main>
    </>
  )
}

export default Home;
